# Generated by Django 2.2.10 on 2020-06-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientnum',
            name='cid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='clientnum',
            name='num',
            field=models.IntegerField(null=True),
        ),
    ]
