# Generated by Django 2.2.10 on 2020-06-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200622_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientnum',
            name='cid',
            field=models.IntegerField(null=True, verbose_name='客户端id'),
        ),
        migrations.AlterField(
            model_name='clientnum',
            name='num',
            field=models.IntegerField(null=True, verbose_name='分数'),
        ),
    ]
